#!/bin/bash

export PATH=$PATH:/opt/couchbase/bin:/opt/couchbase/bin/tools:/opt/couchbase/bin/install:/usr/local/bin/
service() {
   if [ "$1" == "stop" ]; then
      ps aux | grep couchbase | grep -v grep | grep -v systemctl | awk '{print $2}' | xargs kill
      echo "couchbase service stopped"
   fi
   
   if [ "$1" == "start" ]; then
      nohup couchbase-start couchbase-server -- -noinput > /opt/_status 2>&1 </dev/null &
      echo "couchbase service started"
   fi
}

if [ "$2" == "couchbase.service" ]; then
   service $1
elif [ "$2" == "couchbase-server.service" ]; then
   service $1
else
   if [ "$0" == "/usr/sbin/reboot" ]; then
       # fake reboot
       service stop
       sleep 10
       service start
   else
       exec /bin/systemctl.bin "$@"
   fi
fi
